handler/ndnp.py
When loading NDNP data, allow for the reel-related elements to not be populated, and in such cases, do not create any triples relating to reels.
Also, do not create logs for the later creation of reel objects.
=> LIBFCREPO-520

README.md, plastron/commands/imgsize.py, plastron/util.py, requirements.txt
Loads binaries from URIs in the repository, uses PIL to determine a width and height, then PATCHes the repository metadata to add those dimensions using ebucore RDF predicates.
https://issues.umd.edu/browse/LIBFCREPO-578
=> LIBFCREPO-578. Added imgsize command.

plastron/util.py
RFC 3230 and the Fedora API specify "sha" as the parameter name for passing a SHA-1 digest in the Digest header.
https://issues.umd.edu/browse/LIBFCREPO-613
=> LIBFCREPO-613. Fix the Digest header param name.

README.md, plastron/cli.py, plastron/commands/load.py, plastron/handlers/mapped-csv.py, plastron/handlers/ndnp.py, plastron/handlers/turtle.py
* Provide default locations, based on batch.yml's own location, for many options
* The only required options for all handlers to load are now: BATCH_FILE, COLLECTION, and HANDLER
* Handler-specific options are grouped under a HANDLER_OPTIONS key
https://issues.umd.edu/browse/LIBFCREPO-543
=> LIBFCREPO-543. Standardize the batch.yml formats.

plastron/daemon.py, requirements.txt
* Uses a STOMP client to listen for incoming messages
* Spawns separate threads to do the actual exporting (stubbed out for now)
* Sends a completion message back to a different queue on the same message broker
https://issues.umd.edu/browse/LIBFCREPO-694
=> LIBFCREPO-694. Export jobs queue listener.

.dockerignore, .gitignore, Dockerfile, README.md, docker-compose.yml, docker-plastron.yml, docs/cli.md, docs/daemon.md, setup.py
* Based on the python:3.6.2 Docker image
* Uses secrets to pass the client and server certs to the container (requires it to be run in docker swarm mode)
* Includes a config file that contains settings for fcrepo-vagrant servers
* Adds a plastrond entry point in setup.py
* Split the CLI and daemon documentation
* Ensure that stomp.py is in the requirments section of setup.py
https://issues.umd.edu/browse/LIBFCREPO-700
=> LIBFCREPO-700. Created Docker configuration for plastron daemon.

.dockerignore, Dockerfile, docker-compose.yml
Helps decouple configuration from the image build.
https://issues.umd.edu/browse/LIBFCREPO-709
=> LIBFCREPO-709. Use a docker config for plastrond.yml file.

plastron/commands/export.py
https://issues.umd.edu/browse/LIBFCREPO-711
=> LIBFCREPO-711. Follow the describedby link header to allow export of metadata on binaries.

plastron/authority.py, plastron/commands/export.py, plastron/http.py, plastron/models/letter.py, plastron/models/poster.py, plastron/namespaces/__init__.py, plastron/rdf.py, plastron/serializers.py
* Moved serializer classes into plastron.serializers module
* Omit server-managed triples from export command
* Add RDF model capability to read objects from a graph
* Object properties can have an obj_class
* Embedded object_properties with an obj_class get read into the model at the same time as their parent object
* Used a metaclass to make the RDF property inheritance work correctly
* Made values() method a generator
* Include subject URI and index of hash URIs in CSV output
* Always back properties with a values array
* Added Letter and Poster models
* Add additional language columns when serializing to CSV
* Remove completely unused columns from CSV export
* Auto-detect the plastron model class to use based on the RDF type of the graph
https://issues.umd.edu/browse/LIBFCREPO-695
=> LIBFCREPO-695. Content-model-based CSV export.

plastron/commands/export.py, plastron/daemon.py, plastron/serializers.py
* Configure public URI template from a command argument that is then passed to the serializer.
* Read from the config file or fall back to getting the PUBLIC_URI_TEMPLATE from the environment.
https://issues.umd.edu/browse/LIBFCREPO-720
=> LIBFCREPO-720. Add configurable public URI template.

plastron/commands/delete.py, plastron/commands/list.py, plastron/commands/load.py, plastron/commands/update.py, plastron/http.py, plastron/util.py
* Use hyphens in dry-run, no-transactions, no-binaries, and no-annotations flags
* Use action=store_false plus more descriptive destinations to make the negative options more readable in code
* Return the target URI in the recursive_get (so binaries return their fcr:metadata URI)
* Move transaction commit/rollback handling into the process_list method
* Handle exceptions in the update command
* Use a lightweight http.Resource namedtuple-based class to hold a URI and the describedby URI thereof
https://issues.umd.edu/browse/LIBFCREPO-734
=> LIBFCREPO-734. Fixes and improvements to the CLI.

plastron/cli.py, plastron/commands/import.py, plastron/ldp.py, plastron/rdf.py
- allow chaining of attribute lookups of RDF properties
- print the cli header and footer on stderr instead of stdout
- use set difference to calculate deletes/inserts for simple columns
- import includes a limit argument for the number of rows to read
- import uses an object lookup index for setting properties on embedded objects
- RDFObjectProperty can use index notation to look up object by URI
https://issues.umd.edu/browse/LIBFCREPO-755
=> LIBFCREPO-755. Added an import command.

plastron/commands/load.py, plastron/handlers/mapped-csv.py, plastron/handlers/ndnp.py, plastron/handlers/reel.py, plastron/handlers/turtle.py, plastron/ldp.py, plastron/models/letter.py, plastron/models/newspaper.py, plastron/models/poster.py, plastron/oa.py, plastron/ore.py, plastron/pcdm.py, plastron/rdf.py, plastron/validation/__init__.py, plastron/validation/rules.py
- removed explicit setting of multivalued property
- add default class attributes to property classes
- renamed collections and components to member_of and members to align with PCDM terminology
- implement proxy and aggregation through a separate class
- change get_term to a class method for data and object properties
- added validation rules for min_len, max_len, exactly, required, allowed_values, and from_vocabulary
- rules are applied using an external ruleset, and not defined in the model class itself
- vocabulary fetch for from_vocabulary rule use an LRU cache
https://issues.umd.edu/browse/LIBFCREPO-722
=> LIBFCREPO-722. Property validation.

docker-plastron.yml, docs/cli.md
Based on the code in the "__init__" method of the "CommandListener"
class in "plastron/stomp/listeners.py", changed the "COMPLETED_JOBS"
property in "docker-plastron.yml" from "JOBS_COMPLETED" to
"COMPLETED_JOBS". Without this change, the Docker container reports
an error and continuously restarts.
Also fixed some mismatched code blocks in docs/cli.md.
https://issues.umd.edu/browse/LIBFCREPO-763
=> LIBFCREPO-763. Fixed "JOBS_COMPLETED" property in docker-plastron.yml

plastron/commands/import.py, plastron/exceptions.py, plastron/models/newspaper.py, plastron/rdf.py, plastron/validation/__init__.py, plastron/validation/rules.py
- plastron import always attempts to run validation on each item from the import file
- added a function validation rule that can call an arbitrary callable to check property values
- renamed *_len rules to *_values
- if no ruleset is given to validate, check the object itself for a default VALIDATION_RULESET attribute
- added a validation-only mode to plastron import
- added a basic validation ruleset to the newspaper issue model
https://issues.umd.edu/browse/LIBFCREPO-768
=> LIBFCREPO-768. Added validation to the plastron import command.

plastron/commands/import.py, plastron/models/__init__.py, plastron/models/newspaper.py, plastron/models/umd.py, requirements.txt, setup.py
- create a new object when there is no URI in the CSV spreadsheet
- includes support for creation of new embedded objects
- added --make-template option to import command that makes a CSV template using the header map from the given model
- use argparse.FileType for file-like CLI arguments; enables us to pass a file-like handle of the STOMP message body string
- added UMD Item model
https://issues.umd.edu/browse/LIBFCREPO-758
=> LIBFCREPO-758. Create new objects via import command.

docs/cli.md, plastron/commands/export.py, plastron/commands/import.py, plastron/serializers.py, plastron/stomp/listeners.py
- use argparse FileType arguments for export output file
- pass around file handles instead of names
https://issues.umd.edu/browse/LIBFCREPO-770
=> LIBFCREPO-770. Standardized the process_message method into the command listener.

plastron/commands/import.py, plastron/http.py
Moved the build_sparql_query method to the Repository object so it can add transaction ids to subject URIs as needed.
https://issues.umd.edu/browse/LIBFCREPO-775
=> LIBFCREPO-775. Include transaction id in SPARQL Update queries.

plastron/serializers.py
https://issues.umd.edu/browse/LIBFCREPO-779
=> LIBFCREPO-779. Ensure that file is open in binary mode for Turtle serializer.

plastron/commands/import.py, plastron/stomp/listeners.py
Use message status "Error" for any caught exceptions.
https://issues.umd.edu/browse/LIBFCREPO-785
=> LIBFCREPO-785. Raise DataReadExceptions for unrecognized CSV headers.

plastron/cli.py, plastron/commands/import.py
Otherwise, the Archelon STOMP client will complain about an empty header field and fail to process the message.
Also, when constructing the index in validation-only mode of existing objects, create embedded objects as needed.
https://issues.umd.edu/browse/LIBFCREPO-798
=> LIBFCREPO-798. Ensure there is an exception message on validation failure.

plastron/commands/import.py
A CSV file originating in Excel may have a Unicode "byte order mark"
(BOM) that throws off the parsing of the file.
Following the advice in https://stackoverflow.com/a/40310236, modified
the code to generate the message body using a "utf-8-sig" encoding,
which ameliorates the issue.
https://issues.umd.edu/browse/LIBFCREPO-801
=> LIBFCREPO-801. Added "utf-8-sig" encoding for parsing CSV imports

plastron/commands/import.py, plastron/models/umd.py, plastron/rdf.py, requirements.txt, setup.py, tests/test_umd_model.py
* Added ability to distinguish predicate to property mappings by the datatype of the literal
* Added pytest as a dev dependency
* Added a test for the accession_number property
https://issues.umd.edu/browse/LIBFCREPO-796
=> LIBFCREPO-796. Added accession_number to UMD Item model.

.gitignore, plastron/daemon.py, plastron/stomp/inbox_watcher.py, plastron/stomp/listeners.py, requirements.txt, setup.py
Added the "watchdog" library to "requirements.txt" and "setup.py".
Used the "watchdog" library to create InboxWatcher/InboxEventHandler classes.
The InboxWatcher is created and started when via the "on_connected" method of the CommandListener class. The InboxEventHandler is set up to respond to the creation of new files, or the modification of existing files, in the "inbox" directory by converting the file into a message and calling the "process_message" method on CommandListener class.
The InboxWatcher is stopped when the via the "on_disconnected" method in CommandListener.
The handling of inbox messages is somewhat changed – all messages now call "process_message" in CommandListener via the InboxWatcher/InboxEventHandler classes. There are two sources of messages:
1) A file (or files) …
=> LIBFCREPO-794. Implemented InboxWatcher to monitor for new messages

docs/cli.md, plastron/commands/import.py, plastron/files.py
* import uses a RemoteFile when binaries-location starts with "sftp:"
https://issues.umd.edu/browse/LIBFCREPO-803
=> LIBFCREPO-803. RemoteFile uses an sftp: URI to specify the remote location.

plastron/commands/import.py, plastron/namespaces/__init__.py, plastron/serializers.py
* If there is not a full name for the language, use the code itself
* If there is not a descriptive name for the datatype, use the CURIE shorted URI
* Recognize these formats on the import side
https://issues.umd.edu/browse/LIBFCREPO-805
=> LIBFCREPO-805. Provide fallback language and datatype header labels.

plastron/models/poster.py
Match the current state of Prange Posters data.
https://issues.umd.edu/browse/LIBFCREPO-808
=> LIBFCREPO-808. Updated Poster content model validation ruleset.

plastron/models/letter.py, plastron/models/poster.py, plastron/models/umd.py, plastron/validation/__init__.py
Moved the is_edtf_formatted and is_valid_iso639_code validation functions into the plastron.validation module.
https://issues.umd.edu/browse/LIBFCREPO-811
=> LIBFCREPO-811. Require EDTF dates for Letter and Poster content models.

plastron/commands/export.py, plastron/files.py, plastron/util.py
- changed binaries_dir to binaries_dest in config
- moved the code to make an ssh connection into plastron.util.get_ssh_client
https://issues.umd.edu/browse/LIBFCREPO-815
=> LIBFCREPO-815. Support sftp: URLs for binaries destination

plastron/commands/export.py, plastron/stomp/inbox_watcher.py, plastron/util.py
- added SSH_PRIVATE_KEY config to the export config
- get_ssh_client() passes on extra keyword args to the SSHClient.connect() method
- auto-add unknown SSH host keys
- inbox watcher only triggers on file modification to prevent double processing
https://issues.umd.edu/browse/LIBFCREPO-815
=> LIBFCREPO-815. Configuration options for SSH/SFTP exports.

plastron/commands/import.py, plastron/stomp/inbox_watcher.py
Also restore the on_created callback to InboxWatcher.
https://issues.umd.edu/browse/LIBFCREPO-817
=> LIBFCREPO-817. Count files even when running in validate-only mode.

docs/cli.md, plastron/commands/import.py, plastron/files.py, tests/test_files.py, tests/test_import_command.py
Also:
- added tests for functions in the import command module.
- removed unused per-class loggers for classes in the plastron.files module
https://issues.umd.edu/browse/LIBFCREPO-820
=> LIBFCREPO-820. Support "zip+sftp:" locations for import files.

plastron/stomp/inbox_watcher.py
When a new file is created on Linux both the "on_created" and
"on_modified" event handlers were being triggered, unlike on Mac OS X
where only the "on_created" event handler was triggered.
Since the expectation is that files in the inbox will only be created
(as opposed to modified manually in-place), the "on_modified" event
handler is redundant, and so was removed.
https://issues.umd.edu/browse/LIBFCREPO-821
=> LIBFCREPO-821. Removed "on_modified" event handler in InboxEventHandler

.dockerignore, plastron/commands/export.py, plastron/serializers.py
CSV serializer takes a binaries_dir argument to prefix the filenames with. Also, updated the .dockerignore file.
https://issues.umd.edu/browse/LIBFCREPO-833
=> LIBFCREPO-833. Extract UUID from URI and use as item-level bag direct

docker-plastron.yml, docs/cli.md, plastron/commands/echo.py, plastron/stomp/inbox_watcher.py, plastron/stomp/listeners.py
Modified "process_message" method in CommandListener to take a "responseHandler" as a method parameter.
The "response_handler" parameter is a higher-order function which handles the actual STOMP response when message processing is complete.
Renamed "get_response_handler" to "asynchronous_response_handler", and updated existing "process_message" callers to pass it to "process_message". This preserves the existing asynchronous functionality.
Added a "synchronous_queue" (configurable via the "SYNCHRONOUS_JOBS" property). Jobs sent to this queue will use the "synchronous_response_handler" which will send the response to the queue specified in the "reply-to" header of the message.
Added code in "on_message" method to send messages on the synchronous queue directly to the message processor, …
=> LIBFCREPO-837. Add synchronous message processing capability to plastrond

plastron/commands/delete.py, plastron/commands/update.py, plastron/util.py
Handle cases where ItemLog (represented by the "self.resources.completed"
variable can be None, to prevent runtime type errors.
Did this instead of setting "self.resources.completed" to an empty array
or set, because that did not seem to be in line with the use of
ItemLog as a single object.
https://issues.umd.edu/browse/LIBFCREPO-841
=> Plastron CLI commands should not require "--coverage" parameter

docs/cli.md, plastron/commands/update.py
Modifed the "update" command to take a "--validate" flag and "--model" argument
("PlastronArg-validate" and "PlastronArg-model" for the REST API).
Modified the "--dry-run" behavior to include running the validation, if the "--validate" (and "--model) flags are provided.
https://issues.umd.edu/browse/LIBFCREPO-840
=> LIBFCREPO-840. Added validation mode to the plastron update command

plastron/commands/update.py
Fixed an issue where only the first validation error was being
returned.
https://issues.umd.edu/browse/LIBFCREPO-840
=> LIBFCREPO-840. Modified error reporting to return multiple errors

plastron/commands/update.py, tests/test_update_command.py
Corrected issue where the following "update" command arguments:
* dry-run
* validate
* use_transactions
would also be parsed as "true", even if a string such as "False" was
provided.
Modified the code to use the "strtobool" function from distutils.utils,
instead of the Python "bool" function.
https://issues.umd.edu/browse/LIBFCREPO-848
=> LIBFCREPO-848. Fixed Plastron daemon "update" command header parsing

plastron/commands/update.py, tests/test_update_command.py
Prevents the plastrond listener thread from just terminating and leaving the application hanging. Also moved the check for the validate and model attributes into the beginning of the execute method, to catch the error earlier.
https://issues.umd.edu/browse/LIBFCREPO-849
=> LIBFCREPO-849. Catch exception if the validation model can't be found.

plastron/models/letter.py, plastron/models/newspaper.py, plastron/models/poster.py, plastron/models/umd.py, plastron/validation/rules.py, tests/test_validation.py
- non_empty casts its values to string before testing for blanks
- made all min values and exactly 1 fields in content model validation rulesets required
- added test for the required rule
https://issues.umd.edu/browse/LIBFCREPO-851
=> LIBFCREPO-851. Fixed required validation rule to mean at least one non-empty value.

plastron/commands/export.py, plastron/models/poster.py, plastron/serializers.py
- Detect resource class when exporting: Ensure that embedded objects are loaded form the graph correctly. Also added an optional fallback argument to the detect_resource_class function. If present, that class will be returned instead of raising an exception.
- Use dc['format'] instead of dc.format; Method call syntax was yielding the actual "format" method of the rdflib.Namespace class.
https://issues.umd.edu/browse/LIBFCREPO-854
=> LIBFCREPO-854. Fixed missing columns in Letter and Poster exports.

plastron/authority.py, plastron/rdf.py
Modified the RDF validation to validate embedded objects (such as
LabeledThing) by passing control to a "validate" method on those
objects.
Added a "validate" method to LabeledThing to handle validation.
https://issues.umd.edu/browse/LIBFCREPO-855
=> LIBFCREPO-855. Modified validation to handle embedded objects

plastron/models/letter.py, plastron/models/poster.py, plastron/validation/__init__.py
Modified the models to match the validation rules in the spreadsheet:
https://docs.google.com/spreadsheets/d/1b7zXCbsydUuhuQYvjVJrBaLHMnl4KVQg9QPw5YSHRP4
https://issues.umd.edu/browse/LIBFCREPO-856
=> LIBFCREPO-856. Align Plastron validation to spreadsheet

plastron/daemon.py, plastron/util.py, tests/test_envsubst.py
The plastron.daemon config dictionary has environment variables substituted when it is loaded form the config file.
https://issues.umd.edu/browse/LIBFCREPO-859
=> LIBFCREPO-859. Created envsubst utility function.

plastron/commands/stub.py
* loads binaries from HTTP sources in a CSV file into the repository as the files of a pcdm:Object
* use transactions
* sets item title to "Stub for {id}"
* skip item if the binary column is blank
* can set pcdm:memberOf to a collection
https://issues.umd.edu/browse/LIBFCREPO-877
=> LIBFCREPO-877. Added plastron "stub" command.

plastron/commands/stub.py
This way, we do not drop any of the input rows from the output CSV, even if the stub resource could not be created.
https://issues.umd.edu/browse/LIBFCREPO-877
=> LIBFCREPO-877. Write the CSV row for skipped rows.

plastron/http.py
Prefer the token over SSL client certs and HTTP Basic auth.
https://issues.umd.edu/browse/LIBFCREPO-900
=> LIBFCREPO-900. Send "Authorization: Bearer ..." header if AUTH_TOKEN is set in repo config.

plastron/handlers/mapped-csv.py, plastron/handlers/ndnp.py, plastron/ldp.py, plastron/pcdm.py
* Takes a BinarySource plus any number of metadata keyword arguments.
* Use this from_source factory method instead of the direct pcdm.File constructor anywhere we are creating a binary from a source.
* Unified the mapped.csv and pcdm versions of get_file_object.
https://issues.umd.edu/browse/LIBFCREPO-908
=> LIBFCREPO-908. Added a from_source class method to ldp.NonRDFSource.

README.md, plastron/cli.py, plastron/commands/reindex.py, plastron/stomp/__init__.py, setup.py
* Requires the use of the plastrond-style config file via the new -c option to the plastron.cli
* There must be a "REINDEXING" destination defined in the BROKER.DESTINATIONS section of the config file
* Added some convenience methods to the plastron.stomp.Broker class
https://issues.umd.edu/browse/LIBFCREPO-910
=> LIBFCREPO-910. Added reindex command to Plastron

plastron/commands/ping.py, plastron/http.py
Use the more specific ConnectionError builtin class.
https://issues.umd.edu/browse/LIBFCREPO-830
=> LIBFCREPO-830. Include an error message when ping fails.

plastron/commands/import.py, tests/test_import_command.py
- Defaults to True for backwards compatibility
- Uses the distutils strtobool to understand various strings as True or False
- If create pages is false, any files are added directly to the item
- Added tests for the add_files method, both with and without create pages
https://issues.umd.edu/browse/LIBFCREPO-946
=> LIBFCREPO-946. CSV import understands CREATE_PAGES flag.

plastron/commands/import.py
Modified the "execute" method so that the "container" variable will
default to the RELPATH entry in the configuration if a "container"
attribute is not provided in args.
https://issues.umd.edu/browse/LIBFCREPO-943
=> LIBFCREPO-943. Provide a default "container", if not specified in "args"

requirements.txt, setup.py, tests/stomp/test_inbox_watcher.py
v0.10.4 of the "watchdog" package had an extensive update to the
"fsevent" observer, which appears to have broken functionality the
Plastron InboxWatcher relies on
(https://github.com/gorakhargosh/watchdog/pull/680).
In https://github.com/gorakhargosh/watchdog/pull/729 it is noted 
hat the watchdog MacOS tests are failing, and that there are
known issues with fsevent.
The problem still exists in the latest current watchdog version
(v1.0.2), so pinning the "watchdog" package to v0.10.3 is the simplest
fix for now.
The "tests/stomp/test_inbox_watcher.py" passed when using v0.10.3, and
fails in v0.10.4 and later, so it can be used to gauge whether
"watchdog" is performing as expected by Plastron.
https://issues.umd.edu/browse/LIBFCREPO-944
=> LIBFCREPO-944. Pinned "watchdog" package to v0.10.3

plastron/commands/import.py, plastron/models/umd.py, plastron/pcdm.py, tests/test_umd_model.py
Calls a "get_new_member" method with the current file rootname and sequence position.
https://issues.umd.edu/browse/LIBFCREPO-950
=> LIBFCREPO-950. Delegate creation of members to the model class.

plastron/validation/__init__.py, setup.py, tests/test_validation.py
The edtf-validate library passes EDTF datetime strings with an hour of "23".
https://issues.umd.edu/browse/LIBFCREPO-952
=> LIBFCREPO-952. Switch to edtf-validate library.

plastron/models/umd.py
https://issues.umd.edu/browse/LIBFCREPO-953
=> LIBFCREPO-953. Use the correct rootname for the body of the pool report email.

plastron/ldp.py
Modified code to ensure that the item being updated has a "resource"
field filled out with a ResourceURI.
This is necessary to prevent an AttributeError when calling the "patch"
method.
https://issues.umd.edu/browse/LIBFCREPO-956
=> LIBFCREPO-956. Ensure item being updated has ResourceURI

plastron/models/umd.py, tests/test_validation.py
Also parameterized the test_required function, so the assertions all happen in their own tests.
https://issues.umd.edu/browse/LIBFCREPO-861
=> LIBFCREPO-861. Added "from_vocabulary" validation rules to Item model.

docs/cli.md
Added examples to the "docs/cli.md" documentation about deleting resources
in both the "flat" and "hierarchical" layouts.
https://issues.umd.edu/browse/LIBFCREPO-966
=> LIBFCREPO-966. Added resource deletion examples to CLI documentation

.gitignore, plastron/commands/__init__.py, plastron/commands/import.py, plastron/files.py, plastron/stomp/listeners.py, tests/commands/test_base_command.py, tests/test_import_command.py
Modified "BaseCommand" class, adding an "override_repo_config" method to allow subclasses to override the generic repository config with a configuration supplied by the command.
In "plastron/commands/import.py", used the "override_repo_config" method to set the layout structure and relpath for the repository, based on the contents of the import message.
In "plastron/stomp/listeners.py" moved the initialization of the "repo" Repository after calling the "override_repo_config" method for the command, so that it will use the overridden configuration.
Also fixed (with Peter Eichman's help) an issue where using "zip" files in the local development environment were not being closed and reopened as expected, leading to an inability to load in binaries from the zip file. …
=> LIBFCREPO-968. Enable Plastron per-import specification of repository structure and relpath

plastron/files.py
When closing, clear the references held by RemoteFileSource, so that
they are not accidentally used again.
https://issues.umd.edu/browse/LIBFCREPO-971
=> LIBFCREPO-971. Clear RemoteFileSource references on close

docs/cli.md, plastron/http.py, plastron/ldp.py, tests/test_http.py
In Kubernetes, the "REST_ENDPOINT" parameter uses an internal
Kubernetes URL to communicate with umd-fcrepo-webapp. This was
causing the internal URL to be added to the fcrepo resource,
which then could not be located.
Modified the code to use a "REPO_EXTERNAL_URL" to enable "forwarding"
if the "REST_ENDPOINT" and "REPO_EXTERNAL_URL" differ in hostname
or protocol. In Kubernetes, the "REPO_EXTERNAL_URL" parameter
should be set to "FCREPO_BASE_URL".
In addition to setting the "X-Forwarded-Host" and
"X-Forwarded-Proto" headers, added functions to swap
the REST_ENDPOINT and forwarded hosts as needed
so that:
1) The forwarded host is used in the fcrepo resources
2) The REST_ENDPOINT is used to communicate with
umd-fcrepo-webapp
https://issues.umd.edu/browse/LIBFCREPO-972
=> LIBFCREPO-972. Modified Plastron to support forwarded host

.dockerignore, .gitignore, docker-compose.yml, docker-plastron.yml, docs/daemon.md, plastron/http.py, tests/test_http.py
Updated the Plastron Docker configuration so that it can run as a "plastron" Docker stack, in concert with the "umd-fcrepo" Docker stack.
Modified the "plastron/http.py" file to support endpoints that include a hostname and port, instead of just a hostname.
https://issues.umd.edu/browse/LIBFCREPO-977
=> LIBFCREPO-977. Updated Docker configuration to work with "umd-fcrepo" Docker stack

plastron/http.py, setup.py, tests/test_transactions.py
* always raise TransactionError exceptions from Transaction methods
* propagate failures back to the main thread via a threading.Event flag
* before sending an HTTP request within a transaction, check to see if the keep-alive thread has failed, and if so raise a FailureException
* include an integration test using HttpServerMock to simulate a failure of the transaction keep-alive ping
https://issues.umd.edu/browse/LIBFCREPO-883
=> LIBFCREPO-883. Catch transaction keep-alive exceptions.

docs/cli.md, plastron/commands/create.py, plastron/commands/mkcol.py, tests/commands/test_create.py, tests/test_transactions.py
Can create at a specific path (PUT) or with an auto-generated path inside a given container (POST).
- use the "-D" option to set data properties
- use the "-O" option to set object properties
- use the "-T" option to set RDF type(s)
- use the "--collection" option as a shortcut to create a pcdm:Collection with a dcterms:title
Includes tests against a mock repository app; also updated the test_transaction tests to use the Flask app-factory-fixture style.
Marked the mkcol command as deprecated.
https://issues.umd.edu/browse/LIBFCREPO-996
=> LIBFCREPO-996. Added a "create" command.

plastron/cli.py, tests/test_cli.py
* Refactored the Plastron command loading functionality into a
"load_commands" function in "plastron/cli.py" to make it more amenable
to testing.
* Modified the "load_commands" function in "plastron/cli.py" to handle the
"importcommand" module, allowing the name used on the command-line to
be "import".
https://issues.umd.edu/browse/LIBFCREPO-1039
=> LIBFCREPO-1039. Fixed "import" command in Plastron CLI

docker-plastron.yml
Configured the "docker-plastron.yml" file to use the "/fcrepo/rest"
endpoint that is now used for the Docker setup.
https://issues.umd.edu/browse/LIBFCREPO-1041
=> LIBFCREPO-1041. Configured docker-plastron.yml to use /fcrepo/rest

docs/import.md, plastron/commands/importcommand.py, plastron/jobs.py, tests/commands/test_get_command_class.py, tests/commands/test_importcommand.py
1) Refactored the following methods out of the "execute" method in plastron.commands.importcommand.Command to facilitate creating mocks for testing:
* create_repo_changeset
* create_import_job
* update_repo
2) Added a "RepoChangeset" data object to hold the results from the "create_repo_changeset" method
3) Modified plastron.jobs.ImportJob:
* Renamed "drop" method to "drop_failed"
* Added a "drop_invalid" method
4) Modified importcommand.Command to use "drop_invalid" method failures occur during validation, and "drop_failed" method when failures occur when communicating with the repository
5) Added unit tests
The "dropped-<timestamp>.log.csv" file was renamed to "dropped-failed-<timestamp>.log.csv". This enables consistent naming for the "invalid" items, which are placed in a …
=> LIBFCREPO-1035. Record invalid import items separately from valid but dropped items

plastron/commands/reindex.py, plastron/http.py, plastron/util.py, tests/test_http.py
Added a "contains" method to the plastron.http.Repository class that
returns True if the given URI string is contained within the repository,
False otherwise. When running in Docker, the method accepts URIs
starting with either the "internal" Kubernetes URL, or the "external"
repository URL.
Modified the "get_resources" method in plastron.util.ResourceList to
use the "contains" method to determine if the resource URI is in the
repository.
Added an "repo_path" method to the plastron.http.Repository class so
that the resource subpath could be retrieved from a resource URI,
regardless of whether the resource URI was an internal Kubernetes URI
or an external URI.
This was necessary so that the "CamelFcrepoPath" passed to the Solr
reindex command would have the correct path regardless of the …
=> LIBFCREPO-1045. Fix Plastron CLI "reindex" command when run via Docker

docs/messages.md, plastron/commands/export.py, plastron/commands/importcommand.py, plastron/commands/update.py, plastron/rdf.py, plastron/stomp/handlers.py, plastron/stomp/listeners.py
- return the PlastronJobState as the "type" key in the result dictionary for the import and export commands
- removed the PlastronJobStatus STOMP message header; an error message can be determined by checking for the presence of a PlastronJobError header
- set result value for the update command
- wrap string values of RDFObjectProperty in a URIRef
https://issues.umd.edu/browse/LIBFCREPO-1048
=> LIBFCREPO-1048. Updates to support Archelon import job workflow.

plastron/commands/export.py
Prevent a connection error from terminating an export.
https://issues.umd.edu/browse/LIBFCREPO-1055
=> LIBFCREPO-1055. Catch and log ConnectionErrors during export.

plastron/commands/importcommand.py, plastron/exceptions.py, plastron/rdf.py, plastron/validation/__init__.py, plastron/validation/rules.py, plastron/validation/vocabularies/__init__.py, plastron/validation/vocabularies/dcmitype.ttl, tests/commands/test_importcommand.py, tests/test_validation.py
- Created a plastron.validation.vocabularies package
- Added the dcmitype vocabulary
- Created ValidationError class for all validation processing exceptions
https://issues.umd.edu/browse/LIBFCREPO-1058
=> LIBFCREPO-1058. Support storing local copies of validation vocabularies.

plastron/stomp/handlers.py, tests/stomp/test_handlers.py
Changed AsynchronousResponseHandler so that inbox/outbox processing
still occurs when a job throws an exception.
In particular, the original message in the "inbox" should be removed,
even when an exception has occurred during the job, so that the job
is not inadvertently repeated (because it was not removed from the
inbox).
https://issues.umd.edu/browse/LIBFCREPO-1065
=> LIBFCREPO-1065. Modify AsynchronousResponseHandler to clean up msg boxes

plastron/commands/importcommand.py, plastron/commands/update.py, plastron/validation/__init__.py, tests/test_update_command.py
Tracks the successful, invalid, and error updates. Also moved the validate() convenience function (with logging) into a common location to be shared by the import and update commands.
https://issues.umd.edu/browse/LIBFCREPO-1063
=> LIBFCREPO-1063. Return a stats dictionary from updates.

plastron/commands/importcommand.py, tests/test_split_escaped.py
Honors the presence of a backslash escape character and treats the following character as not a delimiter character.
https://issues.umd.edu/browse/LIBFCREPO-1067
=> LIBFCREPO-1067. Created split_escaped() function.

Dockerfile, docker-compose.yml, docs/daemon.md, plastron/daemon.py, plastron/web.py
- plastron.daemon only executes a single child thread, based on the command-line argument (stomp or http)
- changed CMD to ENTRYPOINT in the Docker image so that the daemon mode is easily selectable at docker run-time
- changed the plastrond stack to have two containers, plastrond-stomp and plastrond-http
- updated documentation
https://issues.umd.edu/browse/LIBFCREPO-1075
=> LIBFCREPO-1075. Run only one daemon (STOMP or HTTP) in plastrond.

docs/cli.md, plastron/commands/stub.py
Modified the "stub" command to accept local (relative or absolute) file paths
in the "binary_column" read from the CSV file by adding a "get_source" method
returns the appropriate BinarySource (either "HTTPFileSource", "LocalFileSource",
or None), based on the format of the value in the "binary_column" for the row.
Modified the "stub" command to take a "--rename-binary-column" optional
argument, that changes the binary_column name in the CSV output.
This is needed because the binary_column in the output will always
be a URL, while the binary_column in the input may be a filepath
(and thus have a column name that is not descriptive of the output).
https://issues.umd.edu/browse/LIBFCREPO-1076
=> LIBFCREPO-1076. Updated Plastron "stub" command to support Plant Patents ingest

plastron/commands/stub.py, plastron/util.py, tests/test_util.py
Modified the "uri_or_curie" function in "plastron/util.py" to return
a URIRef if a simple URL is provided as an argument. This enables a
simple URL to be provided to the "access" flag of the "stub" command.
Modified the "plastron/commands/stub.py" file, so that the term returned
by by the "uri_or_curie" function is actually used to populate the
RDF type of the item being added, instead of simply using the bare
string provided in the arguments.
https://issues.umd.edu/browse/LIBFCREPO-1084
=> LIBFCREPO-1084. Modified "stub" command to accept URL for "access" flag

Jenkinsfile, plastron/validation/vocabularies/__init__.py, requirements.txt, setup.py, tests/data/form.json, tests/test_validation.py
rdflib < 6.0.0 does not support "308 Permanent Redirect" responses as redirection and instead treats them as errors. This is fixed in rdflib 6.0.0, but that requires Python > 3.7, and Plastron currently uses 3.6.
This PR adds the `httpretty` and `pytest-datadir` libraries as test dependencies, to facilitate testing of specific HTTP request/response chains and to make creating reusable data file fixtures easier.
https://issues.umd.edu/browse/LIBFCREPO-1093
=> LIBFCREPO-1093. Use requests to read remote vocabularies directly.

Dockerfile, requirements.txt
Also bumped PyNaCl version to 1.5.0, and added finer granularity to numpy versions.
https://issues.umd.edu/browse/LIBFCREPO-1104
=> LIBFCREPO-1104. Bump Python version in docker image to 3.7.15 to support arm64 builds.

docs/adr/0002-drop-py36-and-py37-support.md
Architecture Decision Record to drop Python 3.6 and 3.7 support.
https://issues.umd.edu/browse/LIBFCREPO-1096
=> LIBFCREPO-1096. ADR to drop Python 3.6 and 3.7 support.

docs/cli.md, plastron/commands/create.py, plastron/commands/find.py, plastron/util.py, tests/commands/test_find.py, tests/commands/test_find/graph.ttl, tests/test_util.py
* searches a list of URIs for one's whose graph matches all (or any) of the RDF properties given on the command line
* default to match all (--match-all); use "--match-any" flag to change
* provides a count of the number of resources found
* allows recursive search with the '--recursive/-R' flag
* moved parse_data_property and parse_object_property into plastron.util
* updated tests
https://issues.umd.edu/browse/LIBFCREPO-1109
=> LIBFCREPO-1109. Implemented "find" command.

plastron/commands/update.py, tests/test_update_command.py
This addresses the issue where the first model to be used got "stuck", and future updates used that same model, regardless of what the request message headers were set to.
https://issues.umd.edu/browse/LIBFCREPO-1121
=> LIBFCREPO-1121. Set the model class each time update is executed.

plastron/commands/load.py
In https://umd-dit.atlassian.net/browse/LIBFCREPO-672 the class hierarchy was changed, which caused the BatchItem to no longer inherit the rdf.Resource class. Instead, the item's issue variable was inheriting the rdf.Resource, so that's how we're able to obtain the uri and title.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1135
=> LIBFCREPO-1135: Fixing retrieving the URI and Titles

plastron/commands/importcommand.py, plastron/jobs.py, plastron/serializers.py
- Templates generated will now have the ITEM_FILES column in the csv file
- Files in the ITEM_FILES column will now have resources without a page created
- Old files without the ITEM_FILES column will still work
https://umd-dit.atlassian.net/browse/LIBFCREPO-1136
=> LIBFCREPO 1136: Allow import of binaries at the item level

plastron/models/letter.py, plastron/models/newspaper.py, plastron/models/poster.py, plastron/models/umd.py, plastron/validation/__init__.py
Plastron import may be erroring with blank handles because of this key in the models
https://umd-dit.atlassian.net/browse/LIBFCREPO-1166
=> LIBFCREPO-1166: Removing the "exactly" key

plastron/models/letter.py, plastron/models/newspaper.py, plastron/models/poster.py, plastron/models/umd.py
The handles should be under identifier now rather than identifer
https://umd-dit.atlassian.net/browse/LIBFCREPO-1165
=> LIBFCREPO-1165: Fixing spelling issue with identifier

plastron-cli/src/plastron/cli/commands/annotate.py, plastron-repo/src/plastron/jobs/importjob.py
Using new models in Annotate Command to update the PCDM page resource.
Also fixing a naming bug found in the importjob when importing the whpool reports locally.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1218
=>  LIBFCREPO-1218: Updating Modeling in Annotate Command

plastron-cli/src/plastron/cli/commands/imgsize.py, plastron-models/src/plastron/models/umd.py
Updating the imgsize command to use the new transaction models
Also created a new PCDMImageFile class for images. It's a subclass of PCDMFile, with a width and height DataProperty.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1220
=> LIBFCREPO-1220: Updating imgsize command to use new models

plastron-cli/src/plastron/cli/commands/importcommand.py, plastron-cli/tests/commands/test_importcommand.py, plastron-client/src/plastron/client/__init__.py, plastron-client/tests/test_client.py, plastron-client/tests/test_client_error.py, plastron-client/tests/test_endpoint.py, plastron-client/tests/test_functions.py, plastron-client/tests/test_session_header_attribute.py, plastron-repo/pyproject.toml, plastron-repo/src/plastron/jobs/importjob.py, plastron-repo/src/plastron/repo/__init__.py, plastron-repo/src/plastron/repo/pcdm.py, plastron-stomp/README.md, plastron-stomp/compose.yml, plastron-web/Dockerfile, plastron-web/README.md, plastron-web/compose.yml
- builds the docker.lib.umd.edu/plastrond-http image
- split the single docker-compose into two files (one for stomp, one for http)
- removed create_import_job class method
- propagate any errors within a transaction upwards after rolling back
- added a create_page_sequence method to PCDMObjectResource
- added a create_sequence method to AggregationResource
- fix forwarded host to work with ports
- add BeautifulSoup to the plastron-repo requirements
- updated tests and documentation
https://umd-dit.atlassian.net/browse/LIBFCREPO-1236
=> LIBFCREPO-1236. Created separate Dockerfile for plastron-web.

plastron-utils/src/plastron/namespaces/__init__.py
https://umd-dit.atlassian.net/browse/LIBFCREPO-1252
=> LIBFCREPO-1252. Added "umd:" to "http://vocab.lib.umd.edu/model#" namespace mapping.

plastron-cli/src/plastron/cli/commands/importcommand.py, plastron-cli/tests/commands/test_importcommand.py, plastron-repo/src/plastron/jobs/__init__.py, plastron-repo/src/plastron/jobs/imports/__init__.py, plastron-repo/tests/jobs/test_import_job.py, plastron-repo/tests/jobs/test_import_job_utils.py, plastron-stomp/src/plastron/stomp/commands/importcommand.py, plastron-web/src/plastron/web/__init__.py
Forces the published status for every item in the import.
Also modified the import job creation and retrieval process:
- Created an ImportJobs class that is used to create new or load existing jobs
- Use a single `run()` method in ImportJob to run the job, whether starting or resuming
- The differences between starting and resuming are handled completely by the import command modules (CLI and STOMP)
https://umd-dit.atlassian.net/browse/LIBFCREPO-1259
=> LIBFCREPO-1259. Added a --publish flag to the import CLI command.

plastron-repo/src/plastron/jobs/imports/__init__.py, plastron-repo/src/plastron/jobs/imports/spreadsheet.py, plastron-repo/src/plastron/repo/__init__.py
- ContainerResource.create_child() updates the URI of the description after creation
- omit placeholder "urn:uuid:..." URIs in the dropped/failed logs
- other fixes to the ImportSpreadsheet and ImportJob classes
https://umd-dit.atlassian.net/browse/LIBFCREPO-1267
=> LIBFCREPO-1267. Fix logging of URIs for import.

plastron-rdf/src/plastron/rdfmapping/resources.py, plastron-rdf/tests/test_resources.py, plastron-repo/src/plastron/jobs/importjob/spreadsheet.py, plastron-repo/src/plastron/repo/pcdm.py
- add_properties appends the given properties to existing properties
- set_properties clears the existing properties before adding the given properties
- the resource constructor uses add_properties to add defaults and any kwargs
- when importing and existing item, uses set_properties to replace the existing data with the values from the spreadsheet
https://umd-dit.atlassian.net/browse/LIBFCREPO-1274
=> LIBFCREPO-1274. Created separate add_properties and set_properties methods.

plastron-client/src/plastron/client/__init__.py, plastron-repo/src/plastron/jobs/importjob/__init__.py, plastron-repo/src/plastron/repo/pcdm.py, plastron-repo/tests/jobs/test_import_job.py, plastron-stomp/src/plastron/stomp/commands/importcommand.py
- Eliminate "seek on closed file" errors by constructing the digest and other headers outside of the context manager that reads the source file.
- Improve the STOMP import command:
- When resuming an import job via STOMP, update the config with values from the command message
- Read the container path from the "relpath" message argument
- More tests for the ImportJob class
- More debug logging
https://umd-dit.atlassian.net/browse/LIBFCREPO-1282
=> LIBFCREPO-1282. STOMP import fixes.

plastron-web/src/plastron/web/__init__.py
Since we are no longer reusing the CLI commands for the webapp, we don't need the wrapper.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1286
=> LIBFCREPO-1286. Don't wrap the PlastronContext in a Namespace for the webapp.

plastron-models/src/plastron/models/letter.py, plastron-models/src/plastron/models/newspaper.py, plastron-models/src/plastron/models/poster.py, plastron-models/src/plastron/models/umd.py, plastron-models/tests/test_issue_model.py, plastron-models/tests/test_letter_model.py, plastron-models/tests/test_poster_model.py, plastron-models/tests/test_presentation_set.py, plastron-models/tests/test_umd_model.py
Added repeatable "presentation_set" field to the "Item" model, that uses the "ore.isAggregatedBy" predicate
(<http://www.openarchives.org/ore/1.0/vocabulary#ore-is-aggregated-by>)
Added tests.
In order to the tests to run, added a "set" vocabulary (http://vocab.lib.umd.edu/set#) via Archelon with a "test" term.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1287
=> LIBFCREPO-1287. Added "presentation_set" field to Item model

plastron-cli/README.md, plastron-cli/src/plastron/cli/commands/delete.py, plastron-cli/src/plastron/cli/commands/imgsize.py, plastron-cli/src/plastron/cli/commands/list.py, plastron-models/src/plastron/models/ldp.py, plastron-models/src/plastron/models/newspaper.py, plastron-models/src/plastron/models/ore.py, plastron-models/src/plastron/models/pcdm.py, plastron-models/src/plastron/models/poster.py, plastron-models/src/plastron/models/umd.py, plastron-models/src/plastron/serializers/csv.py, plastron-models/tests/test_issue_model.py, plastron-models/tests/test_letter_model.py, plastron-models/tests/test_poster_model.py, plastron-rdf/src/plastron/rdfmapping/descriptors.py, plastron-rdf/src/plastron/rdfmapping/resources.py, plastron-repo/src/plastron/jobs/exportjob.py, plastron-repo/src/plastron/repo/pcdm.py
Build a lookup table of object class names: In the `__init_subclass__()` method for RDFResourceBase, record the short name of the class being defined and a pointer to the class object in a dictionary. Then use this dictionary to look up object_class values that are given as strings.
Re-enabled skipped model tests, and added test for empty objects too.
Moved classes out of plastron.models.umd into new plastron.models modules:
* Proxy, AggregationMixin --> plastron.models.ore
* LDPContainer --> plastron.models.ldp
* PCDMObject, PCDMFile --> plastron.models.pcdm
https://umd-dit.atlassian.net/browse/LIBFCREPO-1304
=> LIBFCREPO-1304. Fixed failing validation tests for Issue and Poster models.

plastron-cli/tests/commands/test_publish.py, plastron-models/src/plastron/handles/__init__.py, plastron-models/tests/test_handles.py, plastron-repo/docs/handles.puml, plastron-repo/src/plastron/jobs/importjob/__init__.py, plastron-repo/src/plastron/repo/publish.py, plastron-repo/tests/jobs/test_import_job.py, plastron-repo/tests/repo/test_publishable_resource.py
- renamed get_handle() to find_handle() (to look up by repo URI)
- added a get_handle() method (to look up by prefix and suffix)
- raise an error on a 404 response from the handle service (since the "handle not found" condition is relayed via the "exists" key in the response, and not the status code)
- updated handle assignment logic to look up handles from the metadata in the handle service, and update their target URLs if necessary
- created documentation flowchart for the handle assignment process
- added has_handle property to the HandleBearingResource class
- created plastron-repo tests for publishing
https://umd-dit.atlassian.net/browse/LIBFCREPO-1313
=> LIBFCREPO-1313. Fix handle creation and updating when publishing.

plastron-cli/tests/commands/test_importcommand.py, plastron-repo/src/plastron/jobs/importjob/__init__.py, plastron-repo/tests/jobs/test_import_job.py, plastron-repo/tests/jobs/test_import_job/item_with_empty_item_files_column.csv, plastron-repo/tests/jobs/test_import_job/item_with_file_in_item_files_column.csv
This change modifies the import job validation to not
require a "binaries_location" argument for the import job
when a CSV file contains an "FILES" or "ITEM_FILES"
column that has no values.
This change was necessary to support metadata-only imports
(which do not specify a "binaries_location" argument) where the
CSV file being imported was generated from an Archelon export
job (which by default includes an "ITEM_FILES" column).
https://umd-dit.atlassian.net/browse/LIBFCREPO-1322
=> LIBFCREPO-1322. Enable metadata-only import job from exported CSV file

plastron-models/src/plastron/handles/__init__.py, plastron-repo/src/plastron/repo/publish.py, plastron-repo/tests/repo/test_publishable_resource.py, plastron-stomp/src/plastron/stomp/commands/importcommand.py, plastron-stomp/tests/commands/test_importcommand_stomp.py
- the "resolve()" method returns None if the handle is not found on the handle server
- allow a Handle object to be created without a URL
- added "has_url" property to Handle class
https://umd-dit.atlassian.net/browse/LIBFCREPO-1313
=> LIBFCREPO-1313. Replaced "get_handle()" method with "resolve()".

plastron-repo/docs/jobs/import.md, plastron-repo/src/plastron/files/__init__.py, plastron-repo/src/plastron/jobs/importjob/__init__.py, plastron-repo/src/plastron/jobs/importjob/spreadsheet.py, plastron-repo/src/plastron/repo/pcdm.py, plastron-repo/tests/jobs/test_import_job_utils.py
- added label field to the FileGroup class
- changed MetadataError to not be a subclass of JobError
- added a re-raising clause for MetadataErrors that occur during a job as a JobError
- add ability to parse a label for members from the FILES column
https://umd-dit.atlassian.net/browse/LIBFCREPO-1318
=> LIBFCREPO-1318. Custom page labels for import.

plastron-cli/src/plastron/cli/commands/publish.py, plastron-models/src/plastron/models/fedora.py, plastron-repo/src/plastron/context/__init__.py, plastron-repo/src/plastron/jobs/importjob/__init__.py, plastron-repo/src/plastron/jobs/publicationjob.py, plastron-repo/tests/context/test_get_public_url.py, plastron-web/src/plastron/web/activitystream.py
* `path`: the full repository path to the resource
* `container_path`: the repository path to the resource's parent container
* `relpath`: same as `container_path`, but omits the leading "/"
* `uuid`: the UUID portion of the resource's path
https://umd-dit.atlassian.net/browse/LIBFCREPO-1335
=> LIBFCREPO-1335. Enable additional substitution values in public URL template for handle generation.

plastron-cli/src/plastron/cli/commands/export.py, plastron-models/src/plastron/models/fedora.py, plastron-models/src/plastron/serializers/csv.py, plastron-models/tests/serializers/test_csv.py, plastron-rdf/src/plastron/rdfmapping/resources.py, plastron-repo/src/plastron/jobs/exportjob.py, plastron-stomp/src/plastron/stomp/commands/export.py
- pass the entire PlastronContext to the ExportJob so it has access to the get_public_url() method
- added a `redescribe()` method to RDFResourceBase to create a new model object with the same graph and URI
- added more properties to the FedoraResource model class
https://umd-dit.atlassian.net/browse/LIBFCREPO-1346
=> LIBFCREPO-1346. Ensure the PUBLISH and HIDDEN columns get written on export.

plastron-models/src/plastron/models/letter.py, plastron-models/src/plastron/models/newspaper.py, plastron-models/src/plastron/models/poster.py, plastron-models/src/plastron/models/umd.py, plastron-models/tests/test_copyright_notice.py, plastron-utils/src/plastron/namespaces/__init__.py
Added an optional, non-repeatable "copyright_notice" DataProperty field to the "Issue", "Item", "Letter", and "Poster" models, that uses the "schema.copyrightNotice" predicate
(<https://schema.org/copyrightNotice>)
Added the "schema.org" namespace to
"plastron-utils/src/plastron/namespaces/__init__.py" as "schema".
Added tests.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1342
=> LIBFCREPO-1342. Added "copyright_notice" field to models

conftest.py, plastron-models/README.md, plastron-models/src/plastron/models/letter.py, plastron-models/src/plastron/models/newspaper.py, plastron-models/src/plastron/models/poster.py, plastron-models/src/plastron/models/umd.py, plastron-models/src/plastron/validation/vocabularies/__init__.py, plastron-models/tests/data/vocabularies/collection.ttl, plastron-models/tests/data/vocabularies/dcmitype.ttl, plastron-models/tests/data/vocabularies/form.ttl, plastron-models/tests/data/vocabularies/rightsStatement.ttl, plastron-models/tests/data/vocabularies/set.ttl, plastron-models/tests/data/vocabularies/termsOfUse.ttl, plastron-models/tests/test_terms_of_use.py
The `get_vocabulary method` in the `plastron-models/src/plastron/validation/vocabularies/__init__.py` module initializer controls how vocabularies used for validation are retrieved.
Vocabularies used to validate models are retrieved either from the local filesystem, or from a vocabulary server on the network.
The code uses two variables:
* `VOCABULARIES_DIR` - The full filepath to the directory containing the local vocabulary files
* `VOCABULARIES` - A dictionary mapping a URI to the name of the file containing the vocabulary.
Vocabularies matching URIs in the `VOCABULARIES` dictionary are first looked up locally, with the local file being used, if found. If not, a network lookup using the URI as the vocabulary location is used.
Vocabulary URIs not in the `VOCABULARIES` dictionary are …
=> LIBFCREPO-1339. Add a “Terms of Use” field to the content models

plastron-models/tests/test_copyright_notice.py, plastron-utils/src/plastron/namespaces/__init__.py
Changed the "http://schema.org/" namespace to "https://schema.org/" as "https" is the prefix used in the canonical URLs on the schema.org website.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1431
=> LIBFCREPO-1431. Changed namespace to "https://schema.org/"

docs/decisions/0004-resource-publication-and-visibility-via-import.md, plastron-cli/docs/import.md, plastron-repo/src/plastron/jobs/importjob/__init__.py, plastron-repo/tests/jobs/test_import_job.py
Removed code from the
“plastron-repo/src/plastron/jobs/importjob/__init__.py” file where the “publish” and “hidden” fields from individual CSV rows was used to publish/hide items. This included removing code from the “create_resource” method, which set the “umdaccess.Published” and “umdaccess.Hidden” RDF type for newly created items (which was problematic because it was setting the types without doing other “publish” activities such as minting a new handle).
Updated the unit tests, and the “plastron-cli/docs/import.md” file (which had become out-of-date with the current options provided by the “import” command).
Based on the changes in this issue, the “import” command only publishes via the “--publish” flag, which published all the items in the import. There is no way to “hide” (or make …
=> LIBFCREPO-1425. Remove per-row publishing/hiding from Plastron import

plastron-models/pyproject.toml, plastron-models/src/plastron/validation/rules.py, plastron-models/src/plastron/validation/vocabularies/__init__.py, plastron-models/tests/test_is_from_vocabulary.py
- removed "@lru_cache" from `get_subjects()`
- moved call to `get_subjects()` into the body of the validation function
- added httpretty to test dependencies from plastron-models
https://umd-dit.atlassian.net/browse/LIBFCREPO-1447
=> LIBFCREPO-1447. Always get vocabulary at validation function execution time.

plastron-models/src/plastron/models/poster.py, plastron-models/tests/test_poster_model.py, plastron-rdf/src/plastron/rdfmapping/properties.py
- switched the `Poster.subject` attribute to a DataProperty
- added tests
https://umd-dit.atlassian.net/browse/LIBFCREPO-1449
=> LIBFCREPO-1449. Prevent non-Literal values from being added to a DataProperty.

plastron-models/src/plastron/serializers/csv.py, plastron-models/tests/serializers/conftest.py, plastron-models/tests/serializers/test_csv.py, plastron-models/tests/serializers/test_csv_functions.py
- rename CSVSerializer attribute "rows_by_content_model" to "sheets"
- created a Sheet class that encapsulates all the per-sheet metadata that the row_info dictionaries did
- created a ColumnDict class that encapsulates the return value from flatten()
- moved the write_csv_file() function into the Sheet class as a method
- after calling flatten(), add the language tagged columns to the "extra_columns" dictionary
- updated tests
https://umd-dit.atlassian.net/browse/LIBFCREPO-1470
=> LIBFCREPO-1470. Ensure language tagged columns are exported.

plastron-stomp/src/plastron/stomp/commands/importcommand.py
Before, when import jobs would be created, the lack of the private key being set would result in "System Error during Validation" in Archelon for the job status.
Now they should succeed on the first try, without needing to resubmit
https://umd-dit.atlassian.net/browse/LIBFCREPO-1512
=> LIBFCREPO-1512: Moving addition of SSH_PRIVATE_KEY

plastron-cli/src/plastron/cli/commands/importcommand.py, plastron-cli/src/plastron/cli/commands/set.py, plastron-cli/src/plastron/cli/commands/update.py, plastron-cli/tests/commands/test_set.py, plastron-cli/tests/test_embedded_objects.py, plastron-models/pyproject.toml, plastron-models/src/plastron/models/__init__.py, plastron-models/src/plastron/models/umd.py, plastron-models/src/plastron/serializers/__init__.py, plastron-models/tests/serializers/conftest.py, plastron-repo/src/plastron/jobs/exportjob.py, plastron-repo/src/plastron/jobs/importjob/__init__.py, plastron-repo/tests/jobs/test_import_job_utils.py, plastron-repo/tests/jobs/test_metadata_spreadsheet.py, plastron-stomp/src/plastron/stomp/commands/update.py, plastron-stomp/tests/commands/test_update_stomp.py
* Changed model autoloading to use entry points:
- group "plastron.content_models" in pyproject.toml project.entry-points
- format: name = package:class
- renamed `get_model_class()` to `get_model_from_name()`
- added `get_model_from_uri()`
- added `guess_model()`
* Remove the object class from the `member_of` property, since that was causing a circular inclusion loop in solrizer when following the linked objects
- General principle: embed/include from the top down, not bottom up or mixed
https://umd-dit.atlassian.net/browse/LIBFCREPO-1495
=> LIBFCREPO-1495. Updates to support solrizer content model mapping.

plastron-models/src/plastron/models/letter.py, plastron-models/src/plastron/models/poster.py
- ensure that they use the `VocabularyTerm` class for all controlled vocabulary properties
- `Letter` should inherit from `PCDMObject` and `HandleBearingResource`
https://umd-dit.atlassian.net/browse/LIBFCREPO-1499
=> LIBFCREPO-1499. Updated Letter and Poster models.

plastron-cli/src/plastron/cli/__init__.py, plastron-cli/src/plastron/cli/commands/importcommand.py, plastron-repo/src/plastron/context/__init__.py
- example: "plastron/4.4.0 (import)"
- fix position of logging message in the import command class
https://umd-dit.atlassian.net/browse/LIBFCREPO-1582
=> LIBFCREPO-1582. Include the CLI command name in the User-Agent string

plastron-models/pyproject.toml, plastron-models/src/plastron/models/__init__.py, plastron-models/src/plastron/models/letter.py, plastron-models/src/plastron/models/newspaper.py, plastron-models/src/plastron/models/page.py, plastron-models/src/plastron/models/pcdm.py, plastron-models/src/plastron/models/poster.py, plastron-models/src/plastron/models/umd.py
- moved the Page model class into a separate module (plastron.models.pages)
- create a File model class in the plastron.models.pages module
- add ContentModeledResource as a mix-in to Letter, Poster, Issue, Item, Page, and File
- added Page and File content models to the entrypoint definitions for "plastron.content_models"
- added "checksum" property (mapped to premis:hasMessageDigest) to the PCDMFile class
https://umd-dit.atlassian.net/browse/LIBFCREPO-1583
=> LIBFCREPO_1583. Added ContentModeledResource class.

plastron-models/src/plastron/models/newspaper.py
Repeatable, not required, embedded Agent object.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1609
=> LIBFCREPO-1609. Added "rights holder" property to newspaper issue model.

plastron-models/src/plastron/models/umd.py
Fixes an issue where all the keys within it had pcdm prefixed to them
https://umd-dit.atlassian.net/browse/LIBFCREPO-1619
=> LIBFCREPO-1619: Add has_file to Item Class

plastron-cli/README.md, plastron-cli/src/plastron/cli/commands/reindex.py, plastron-messaging/src/plastron/messaging/broker.py
- takes a key used to look up additional routing headers (set in the config file) to send with the reindexing message
- improved the help message display
- added basic debug logging to the Destination.send() method
https://umd-dit.atlassian.net/browse/LIBFCREPO-1620
=> LIBFCREPO-1620. Added `--index` option to `reindex` CLI command.

plastron-jobs/docs/import.md, plastron-jobs/src/plastron/jobs/importjob/__init__.py, plastron-jobs/src/plastron/jobs/importjob/spreadsheet.py, plastron-jobs/tests/jobs/test_import_job_utils.py, plastron-repo/src/plastron/files/__init__.py, plastron-repo/src/plastron/repo/pcdm.py
- page-level and item-level files can have an option "usage tag" in angle brackets
- a usage tag maps to a set of RDF types that are added to that file resource
* "preservation" -> pcdmuse:PreservationMasterFile
* "ocr" -> pcdmuse:ExtractedText
* "metadata" -> fabio:MetadataFile
https://umd-dit.atlassian.net/browse/LIBFCREPO-1625
=> LIBFCREPO-1625. Include file usage information in CSV import.

plastron-cli/tests/commands/test_importcommand.py, plastron-models/src/plastron/models/umd.py, plastron-models/tests/test_umd_model.py
- object property, embedded, repeatable, not required
- predicate is `dcterms:audience`
- object class is `Agent`
https://umd-dit.atlassian.net/browse/LIBFCREPO-1622
=> LIBFCREPO-1622. Added "audience" to the Item content model.

plastron-repo/src/plastron/context/__init__.py, plastron-stomp/Dockerfile, plastron-stomp/src/plastron/stomp/handlers.py
- avoids errors in environments where "plastron-cli" is not installed
- emit the exception traceback in the STOMP message handlers for exceptions that were not handled in the worker thread
- include the top-level VERSION file in the Dockerfile, so the plastron-* packages build correctly
https://umd-dit.atlassian.net/browse/LIBFCREPO-1644
=> LIBFCREPO-1644. Report the "plastron-repo" package version in PlastronContext.version.
