- classes/pcdm.py
https://issues.umd.edu/browse/LIBFCREPO-435
> LIBFCREPO-435. Use requests sessions in the pcdm.Repository class.

- plastron/cli.py
- plastron/pcdm.py
https://issues.umd.edu/browse/LIBFCREPO-485
> LIBFCREPO-485. Added "plastron/{version}" User-Agent string.

- plastron/handlers/turtle.py
https://issues.umd.edu/browse/LIBFCREPO-527
> LIBFCREPO-527. Make sure types is explicitly a list.

- plastron/cli.py
resolves https://issues.umd.edu/projects/LIBFCREPO/issues/LIBFCREPO-545
> make logging config location configurable

- plastron/cli.py
- plastron/commands/load.py
- plastron/handlers/mapped-csv.py
- plastron/pcdm.py
Supersedes #11 
https://issues.umd.edu/browse/LIBFCREPO-555
> LIBFCREPO-555. CSV handler for Plastron.

- plastron/commands/load.py
- plastron/handlers/mapped-csv.py
https://issues.umd.edu/browse/LIBFCREPO-534
> LIBFCREPO-534. Support hierarchical object structures from flat CSV.

- plastron/handlers/mapped-csv.py
- plastron/handlers/ndnp.py
- plastron/handlers/turtle.py
- plastron/logging.py
- plastron/pcdm.py
- plastron/util.py
- requirements.txt
* Created separate BinarySource classes for local files, repository files, and remote (ssh) files.
* CSV column mapping for a filename can now include a "host" parameter that triggers the use of the pcdm.util.RemoteFile binary source class with the specified hostname
https://issues.umd.edu/browse/LIBFCREPO-570
> LIBFCREPO-570. Refactored the pcdm.File class.

- plastron/handlers/mapped-csv.py
https://issues.umd.edu/browse/LIBFCREPO-550
> LIBFCREPO-550. Link collection to top-level items in the batch for the CSV handler.

- requirements.txt
https://issues.umd.edu/browse/LIBFCREPO-617
> LIBFCREPO-617. Update dependency versions.

- plastron/handlers/ndnp.py
https://issues.umd.edu/browse/LIBFCREPO-640
> LIBFCREPO-640. Raise DataReadExceptions when encountering bad XML data.

- plastron/authority.py
- plastron/cli.py
- plastron/commands/extractocr.py
- plastron/commands/load.py
- plastron/handlers/mapped-csv.py
- plastron/handlers/ndnp.py
- plastron/handlers/reel.py
- plastron/handlers/turtle.py
- plastron/http.py
- plastron/ldp.py
- plastron/models/newspaper.py
- plastron/oa.py
- plastron/ore.py
- plastron/pcdm.py
- plastron/rdf.py
- plastron/util.py
* Handlers define Batch and BatchItem classes.
* Reading/writing from/to an RDF graph is handled by a base rdf.Resource class
* Class decorators add declarative mappings of attribute names to RDF predicates
* Rewrite reel handler to work again; re-use Page when building reels
* Moved Repository class into plastron.http module
https://issues.umd.edu/browse/LIBFCREPO-672
> LIBFCREPO-672. Refactor to a decorator-based RDF mapping library.

- plastron/handlers/mapped-csv.py
- plastron/handlers/turtle.py
- plastron/pcdm.py
https://issues.umd.edu/browse/LIBFCREPO-680
> LIBFCREPO-680. Support directories of binaries with CSV handler.

- plastron/commands/delete.py
- plastron/commands/extractocr.py
- plastron/commands/load.py
- plastron/commands/mkcol.py
- plastron/http.py
Used as a context manager, and it will always stop the timing thread no matter what exception is raised.
https://issues.umd.edu/browse/LIBFCREPO-420
> LIBFCREPO-420. Create a Transaction class.

- plastron/commands/load.py
- plastron/http.py
https://issues.umd.edu/browse/LIBFCREPO-420
> LIBFCREPO-420. Fixes to transaction URI handling.

- plastron/commands/export.py
- requirements.txt
- setup.py
https://issues.umd.edu/browse/LIBFCREPO-695
> LIBFCREPO-695. Implement CSV export format.

- plastron/commands/export.py
- plastron/daemon.py
Created Serializer classes for Turtle and CSV.
https://issues.umd.edu/browse/LIBFCREPO-706
> LIBFCREPO-706. Pass export format from message header to export command.

- .gitignore
- docker-plastron.yml
- plastron/commands/export.py
- plastron/daemon.py
* Provides a download URL in the exportjobs.completed message
https://issues.umd.edu/browse/LIBFCREPO-701
> LIBFCREPO-701. plastrond exporter stores export jobs back into the repository.

- plastron/daemon.py
Return a "Failed" message if something goes wrong during the processing of an export.
https://issues.umd.edu/browse/LIBFCREPO-710
> LIBFCREPO-710. Add exception handling.

- Dockerfile
- docker-compose.yml
- docker-plastron.yml
- plastron/commands/export.py
- plastron/daemon.py
* Incoming messages are saved to the file system before being processed
* Outgoing messages are also saved to the file system before being sent
* Saved messages are only removed once they have been processed or sent
* Use futures and a thread pool to do parallel processing of the export requests
* Process messages found in the outbox and inbox when first connected to the broker
* Include /var/opt/plastron as a Docker volume
* The Docker container default config uses /var/opt/plastron/msg/export as its export message storage directory
https://issues.umd.edu/browse/LIBFCREPO-714
> LIBFCREPO-714. Implement guaranteed delivery of messages.

- plastron/daemon.py
* Handle connecting status logs and reconnecting in their own listener.
* Retry connection at startup and not just when disconnected.
https://issues.umd.edu/browse/LIBFCREPO-712
> LIBFCREPO-712. Created ReconnectListener class.

- plastron/commands/load.py
- plastron/commands/mkcol.py
- plastron/http.py
- plastron/ldp.py
- plastron/oa.py
- plastron/ore.py
- plastron/pcdm.py
- plastron/rdf.py
https://issues.umd.edu/browse/LIBFCREPO-716
> LIBFCREPO-716. DRAS-TIC compatibility.

- plastron/models/newspaper.py
- plastron/serializers.py
https://issues.umd.edu/browse/LIBFCREPO-723
> LIBFCREPO-723. Add newspaper issue to the list of recognized models.

- plastron/commands/delete.py
- plastron/commands/update.py
- plastron/util.py
Created a `process_resources()` utility method shared by the `delete` and `update` commands.
https://issues.umd.edu/browse/LIBFCREPO-733
> LIBFCREPO-733. Added update command.

- plastron/commands/delete.py
- plastron/commands/list.py
- plastron/commands/load.py
- plastron/commands/update.py
- plastron/http.py
- plastron/util.py
> Revert "LIBFCREPO-734. Fixes and improvements to the CLI."

- plastron/cli.py
- plastron/commands/delete.py
- plastron/commands/list.py
- plastron/commands/load.py
- plastron/commands/update.py
- plastron/http.py
- plastron/util.py
https://issues.umd.edu/browse/LIBFCREPO-739
> LIBFCREPO-739. Added completed item logging for update and delete.

- plastron/util.py
Use a temp file for recording completed items while in a transaction.
https://issues.umd.edu/browse/LIBFCREPO-741
> LIBFCREPO-741. Transaction-aware item log handling.

- plastron/handlers/turtle.py
- always provide a subject when loading item from graph
- fixed values attribute name
https://issues.umd.edu/browse/LIBFCREPO-756
> LIBFCREPO-756. Fix turtle handler bugs.

- plastron/commands/import.py
- plastron/models/__init__.py
- plastron/rdf.py
- plastron/serializers.py
- export includes datatype column headers, similar to language headers
- datatype is part of the value, not the property definition
https://issues.umd.edu/browse/LIBFCREPO-757
> LIBFCREPO-757. Support import of columns with language tags or datatypes.

- plastron/commands/export.py
- plastron/commands/import.py
- plastron/daemon.py
- plastron/logging.py
https://issues.umd.edu/browse/LIBFCREPO-759
> LIBFCREPO-759. Log status updates for export and import over STOMP.

- config/templates/batch.yml
- config/templates/correspondence.yml
https://issues.umd.edu/browse/LIBFCREPO-762
> LIBFCREPO-762. Update config/templates files with new LOG_DIR key 

- plastron/commands/export.py
- plastron/daemon.py
- plastron/stomp/__init__.py
- plastron/stomp/listeners.py
https://issues.umd.edu/browse/LIBFCREPO-760
> LIBFCREPO-760. Support generic PlastronCommand, PlastronJobId, and PlastronArg-* headers.

- plastron/commands/export.py
- plastron/commands/import.py
- plastron/daemon.py
- plastron/logging.py
- added an execute method to the import and export commands that yields status info for each item processed
- added exceptions for error conditions inside the command
https://issues.umd.edu/browse/LIBFCREPO-759
> LIBFCREPO-759. Send status messages from Plastron Daemon using STOMP.

- plastron/pcdm.py
https://issues.umd.edu/browse/LIBFCREPO-765
> LIBFCREPO-765. Restore pcdm:Object RDF type.

- plastron/commands/import.py
https://issues.umd.edu/browse/LIBFCREPO-772
> LIBFCREPO-772. In a validate-only mode import, don't connect to repo.

- plastron/commands/import.py
- added a file argument to execute() to pass in a file-like object
- pass the message body (containing the CSV) to execute as a io.StringIO object
https://issues.umd.edu/browse/LIBFCREPO-774
Note: this PR also includes the changes from https://issues.umd.edu/browse/LIBFCREPO-773, and probably supercedes PR #69
> LIBFCREPO-774. Added process_message method to import command.

- docker-plastron.yml
- docs/daemon.md
- plastron/commands/export.py
- plastron/commands/import.py
- plastron/stomp/listeners.py
Added JOB_STATUS destination to plastrond config for Docker.
https://issues.umd.edu/browse/LIBFCREPO-776
> LIBFCREPO-776. Parameterize the job status destination name.

- plastron/commands/import.py
- plastron/ldp.py
Delay creation of the new item until after the validation phase.
https://issues.umd.edu/browse/LIBFCREPO-775
> LIBFCREPO-775. Do item creation and updating within a transaction.

- docs/cli.md
- docs/daemon.md
- docs/messages.md
- plastron/commands/import.py
Otherwise, return None for the total (in JSON, null).
https://issues.umd.edu/browse/LIBFCREPO-777
> LIBFCREPO-777. Get total row count if import file handle is seekable.

- plastron/commands/import.py
For new items, iterate the list of RDF classes in the model and add those to the insert graph.
https://issues.umd.edu/browse/LIBFCREPO-782
> LIBFCREPO-782. Add RDF classes to new items.

- plastron/cli.py
- plastron/daemon.py
- plastron/http.py
- plastron/stomp/listeners.py
Changed daemon setup to instantiate a new repo object for each message, for thread safety.
https://issues.umd.edu/browse/LIBFCREPO-780
> LIBFCREPO-780. Support sending On-Behalf-Of header.

- plastron/commands/import.py
https://issues.umd.edu/browse/LIBFCREPO-781
> LIBFCREPO-781. Record the created and updated URIs from import.

- plastron/commands/import.py
- plastron/util.py
Also, use empty URI <> for item URI in SPARQL update graphs.
https://issues.umd.edu/browse/LIBFCREPO-788
> LIBFCREPO-788. Specify access class using URI or CURIE in N3 format.

- plastron/commands/import.py
- plastron/exceptions.py
- plastron/ore.py
- plastron/rdf.py
- plastron/serializers.py
- plastron/util.py
* include rdf_type as a standard object property of rdf.Resource
* return the proxy resource when appending a proxy to an aggregation
* use plastron methods to recursively create and update new objects
* create one page per file and add to the item
* use the document order in the CSV file to create page order
* added "FILES" to the system headers
https://issues.umd.edu/browse/LIBFCREPO-791
> LIBFCREPO-791. Import binaries from local file system.

- plastron/models/umd.py
Validation rules: at most one value.
https://issues.umd.edu/browse/LIBFCREPO-795
> LIBFCREPO-795. Added bibliographic_citation data property to Item model.

- docs/cli.md
- plastron/commands/export.py
- plastron/commands/imgsize.py
- plastron/commands/import.py
- plastron/files.py
- plastron/handlers/mapped-csv.py
- plastron/handlers/ndnp.py
- plastron/models/newspaper.py
- plastron/pcdm.py
- plastron/util.py
* during import, choose binary source type based on binaries location URI scheme
* refactored binary sources and subclasses into plastron.files module
https://issues.umd.edu/browse/LIBFCREPO-797
> LIBFCREPO-797. Added ZipFile class.

- plastron/models/letter.py
- plastron/models/poster.py
https://issues.umd.edu/browse/LIBFCREPO-799
> LIBFCREPO-799. Added basic validation rulesets for Letter and Poster.

- Dockerfile.ci
- Jenkinsfile
Added Dockerfile.ci and Jenkinsfiles to control
the Plastron build in Jenkins.
https://issues.umd.edu/browse/LIBFCREPO-804
> LIBFCREPO-804. Added Dockerfile.ci/Jenkinsfile

- plastron/serializers.py
ZIP and Turtle require binary, while CSV requires text mode.
https://issues.umd.edu/browse/LIBFCREPO-807
> LIBFCREPO-807. Ensure export output files are opened in the correct mode.

- plastron/commands/import.py
Refactored *_count variables into a single dictionary.
https://issues.umd.edu/browse/LIBFCREPO-810
> LIBFCREPO-810. Count created and updated items separately.

- plastron/models/letter.py
- plastron/models/poster.py
In the Letter and Poster content models.
https://issues.umd.edu/browse/LIBFCREPO-812
> LIBFCREPO-812. Subject and location fields can have multiple values.

- docs/daemon.md
- plastron/commands/export.py
- plastron/commands/import.py
- plastron/daemon.py
- plastron/http.py
- plastron/ldp.py
- plastron/ore.py
- plastron/pcdm.py
- plastron/rdf.py
- plastron/serializers.py
- plastron/stomp/listeners.py
https://issues.umd.edu/browse/LIBFCREPO-802
> LIBFCREPO-802. Export binaries.

- plastron/commands/export.py
- plastron/commands/import.py
Only create one page for each unique basename.
https://issues.umd.edu/browse/LIBFCREPO-809
> LIBFCREPO-809. Group files by basename.

- plastron/commands/import.py
https://issues.umd.edu/browse/LIBFCREPO-817
> LIBFCREPO-817. Count the number of files added during import.

- plastron/commands/import.py
Distinguish between multiple Literal or URIRef values for a property from multiple embedded objects for a property (with their own Literal and URIRef properties).
https://issues.umd.edu/browse/LIBFCREPO-816
> LIBFCREPO-816. Fix embedded object updating.

- requirements.txt
- setup.py
https://issues.umd.edu/browse/LIBFCREPO-818
> LIBFCREPO-818. Updated Pillow required minimum version to 6.2.2

- plastron/commands/import.py
- plastron/files.py
- tests/test_import_command.py
Moved get_source and add_files into the import.Command class.
https://issues.umd.edu/browse/LIBFCREPO-822
> LIBFCREPO-822. Pass ssh options to RemoteFile and ZipFile.

- plastron/handlers/mapped-csv.py
removes obsolete reference to pcdm.Item
> LIBFCREPO-824

- docs/cli.md
- docs/daemon.md
- plastron/commands/export.py
- plastron/serializers.py
- requirements.txt
- setup.py
Output destination can be a local file or SFTP URI.
https://issues.umd.edu/browse/LIBFCREPO-832
> LIBFCREPO-832. Write a single compressed BagIt bag as export output.

- plastron/commands/import.py
- tests/test_import_command.py
https://issues.umd.edu/browse/LIBFCREPO-834
> LIBFCREPO-834. Filter out empty strings when parsing column values.

- plastron/commands/update.py
Modified the "update" command to be runnable via the daemon.
Due to the presence of line breaks in the SPARQL query, it did not seem
feasible the SPARQL query via the "PlastronArg-update-query" header.
Instead, passed the SPARQL query in the message body, along with the
URIs. A typical message body looks like:
```
{
"uri":["https://fcrepolocal/fcrepo/rest/pcdm/93/c8/cf/f5/93c8cff5-3ea3-442b-bde3-d1e493b8d998"],
"sparql_update":"DELETE {...} INSERT {... } WHERE {}"
}
```
https://issues.umd.edu/browse/LIBFCREPO-839
> LIBFCREPO-839. Modified "update" command to run in daemon

- plastron/models/umd.py
https://issues.umd.edu/browse/LIBFCREPO-857
> LIBFCREPO-857. Archival collection should not be an embedded property.

- plastron/commands/export.py
Raises a failure exception if there are any SSHExceptions raised while creating the SFTPClient and opening the remote file.
Also increased the logging level for the export destination to info.
https://issues.umd.edu/browse/LIBFCREPO-860
> LIBFCREPO-860. Add ssh error checking on export.

- plastron/commands/import.py
Ensure that they are only added if they have at least one non-empty property.
https://issues.umd.edu/browse/LIBFCREPO-865
> LIBFCREPO-865. Add new hash resources to graph in a second pass.

- plastron/commands/export.py
- plastron/commands/imgsize.py
- plastron/commands/import.py
- plastron/exceptions.py
- plastron/files.py
- plastron/handlers/mapped-csv.py
- plastron/handlers/ndnp.py
- plastron/models/newspaper.py
- plastron/pcdm.py
- tests/test_files.py
- tests/test_import_command.py
- tests/test_update_command.py
* converted BinarySources into real context managers
* added a StringSource
https://issues.umd.edu/browse/LIBFCREPO-880
> LIBFCREPO-880. Added an HTTPFileSource binary source.

- plastron/commands/extractocr.py
- plastron/commands/import.py
- plastron/commands/load.py
- plastron/commands/mkcol.py
- plastron/http.py
- plastron/ldp.py
- plastron/ore.py
- plastron/pcdm.py
- allow creation of resources by repository path instead of full URI
- pluggable creator strategy (flat or hierarchical)
https://issues.umd.edu/browse/LIBFCREPO-879
> LIBFCREPO-879. Per-import configuration of parent container.

- plastron/commands/stub.py
Include the CSV header in the output file.
https://issues.umd.edu/browse/LIBFCREPO-877
> LIBFCREPO-877. Support setting the access class for stub resources.

- docs/cli.md
- plastron/http.py
- requirements.txt
- setup.py
https://issues.umd.edu/browse/LIBFCREPO-932
> LIBFCREPO-932. Generate 1-hour JWTs using plastron.

- plastron/daemon.py
- plastron/stomp/__init__.py
- plastron/stomp/handlers.py
- plastron/stomp/inbox_watcher.py
- plastron/stomp/listeners.py
- plastron/stomp/messages.py
- tests/test_update_command.py
- add response handler classes for STOMP messaging
- check for exceptions when the executor future resolves
- added a MessageProcessor class
- let the message processor exceptions be handled by the response handler callback
- rename progress and status destinations
- created a Destination class that encapsulates a broker and a destination name for easy sending of messages
- moved message classes to their own module
https://issues.umd.edu/browse/LIBFCREPO-941
> LIBFCREPO-941. Enhance error checking in plastrond.

- plastron/commands/annotate.py
- plastron/http.py
- plastron/ldp.py
- plastron/oa.py
- requirements.txt
- setup.py
- Uses BeautifulSoup to extract the text of an HTML file and create an annotation
- The annotation target is the whole page object
- Updated the FlatCreator to place proxies and annotations inside their targets, for better management
https://issues.umd.edu/browse/LIBFCREPO-951
> LIBFCREPO-951. Created annotate command.

- plastron/cli.py
- plastron/commands/reindex.py
https://issues.umd.edu/browse/LIBFCREPO-954
> LIBFCREPO-954. Send rdf types when reindexing.

- plastron/commands/import.py
- plastron/ldp.py
- plastron/pcdm.py
https://issues.umd.edu/browse/LIBFCREPO-955
> LIBFCREPO-955. Extract text from HTML and annotate during import.

- requirements.txt
- setup.py
https://issues.umd.edu/browse/LIBFCREPO-965
> LIBFCREPO-965. Add rdflib-jsonld to required packages.

- plastron/commands/import.py
- plastron/commands/load.py
- plastron/exceptions.py
- plastron/files.py
- plastron/handlers/mapped-csv.py
- plastron/handlers/turtle.py
- plastron/http.py
- tests/test_files.py
https://issues.umd.edu/browse/LIBFCREPO-961
> LIBFCREPO-961. Check that all files exist during import validation.

- plastron/commands/import.py
https://issues.umd.edu/browse/LIBFCREPO-967
> LIBFCREPO-967. Use only the basename for the title of file resources.

- plastron/commands/import.py
- tests/test_import_command.py
If a column in an import CSV has no datatype, and its corresponding property in the model class does, use the datatype defined in the model class for values in that column.
Also refactored the build_fields() function to take a model class as its second argument, instead of the property_attrs lookup dictionary. It was the only place where that dictionary was used, and it was moved inside of build_fields as an implementation detail.
https://issues.umd.edu/browse/LIBFCREPO-973
> LIBFCREPO-973. Use the model datatype as the default.

- plastron/models/umd.py
- tests/test_umd_model.py
https://issues.umd.edu/browse/LIBFCREPO-990
> LIBFCREPO-990. Check format field to determine if an Item is a pool report.

- plastron/commands/export.py
- plastron/serializers.py
Defaults to the Item model if there is not a more specific model detectable via the rdf:type.
https://issues.umd.edu/browse/LIBFCREPO-992
> LIBFCREPO-992. Export falls back to the Item model.

- plastron/commands/import.py
https://issues.umd.edu/browse/LIBFCREPO-1000
> LIBFCREPO-1000. Assume TIFFs are PreservationMasterFile.

- plastron/commands/reindex.py
- plastron/util.py
Also log the currently reindexing item.
https://issues.umd.edu/browse/LIBFCREPO-1013
> LIBFCREPO-1013. Skip resources that are outside the repo endpoint.

- docs/import.md
- plastron/commands/import.py
- Specify a percentage to import via the -% or --percent command line options, or the PlastronArgs-percent STOMP header
- Selects an evenly spaced subset of the remaining items whose size is equal to the specified percentage of the size of the whole set
- Can run multiple times an load different items each time
https://issues.umd.edu/browse/LIBFCREPO-980
> LIBFCREPO-980. Implement percentage import.

- plastron/cli.py
https://issues.umd.edu/browse/LIBFCREPO-1026
> LIBFCREPO-1026. Call envsubst when loading CLI config.

- .dockerignore
- .gitignore
https://issues.umd.edu/browse/LIBHYDRA-430
> LIBHYDRA-430. Update .dockerignore and .gitignore.

- plastron/jobs.py
- tests/test_import_job.py
https://issues.umd.edu/browse/LIBFCREPO-1033
> LIBFCREPO-1033. Create URL-escaped safe_id from job id string.

- plastron/commands/__init__.py
- plastron/stomp/listeners.py
- tests/commands/test_get_command_class.py
Implements the special case of the import command having the module name "importcommand".
https://issues.umd.edu/browse/LIBFCREPO-1039
> LIBFCREPO-1039. Added a get_command_class function.

- plastron/commands/importcommand.py
- plastron/jobs.py
- plastron/util.py
- tests/commands/test_importcommand.py
- moved the dropped logging into the ImportRun class
- stringify an ImportJob to its id
- use pathlib in the plastron.jobs module
https://issues.umd.edu/browse/LIBFCREPO-1036
> LIBFCREPO-1036. Created ImportRun class.

- docker-plastron-template.yml
- plastron/daemon.py
- plastron/web.py
Log a warning and respond with an empty jobs list.
https://issues.umd.edu/browse/LIBFCREPO-1043
> LIBFCREPO-1043. Handle jobs dir not found.

- plastron/stomp/__init__.py
https://issues.umd.edu/browse/LIBFCREPO-1057
> LIBFCREPO-1057. Handle additional exceptions when sending a STOMP message.

- plastron/daemon.py
- plastron/stomp/__init__.py
- plastron/stomp/handlers.py
- plastron/stomp/listeners.py
- plastron/stomp/messages.py
- tests/stomp/test_messages.py
- tests/test_import_command.py
- attributes that are mapped to headers (e.g., PlastronJobId => job_id) are done dynamically through properties
- using the attributes instead of the raw headers will help ensure consistent header usage
- added PlastronResponseMessage and PlastronErrorMessage classes
https://issues.umd.edu/browse/LIBFCREPO-1062
> LIBFCREPO-1062. Improve the message classes.

- plastron/handlers/mapped-csv.py
No longer assume that the top-level column mapping (self.mapping) is the correct one.
https://issues.umd.edu/browse/LIBFCREPO-1065
> LIBFCREPO-1065. Pass current mapping to get_column_value.

- plastron/daemon.py
- plastron/stomp/__init__.py
- plastron/stomp/listeners.py
Removed the code that tried to automatically reconnect to the STOMP broker. Instead, we will let whatever orchestrator is running plastrond manage the restarts (Docker Swarm for local docker, Kubernetes for test/qa/production deployment).
https://issues.umd.edu/browse/LIBFCREPO-1070
> LIBFCREPO-1070. Halt plastrond when the STOMP connection is disconnected.

- docs/configuration.md
- plastron/cli.py
- plastron/commands/verify.py
- setup.py
The verify command will:
- take a completed mapfile
- Query the URI's
- List URI's which weren't found in SOLR.
Requires a SOLR section with a URL sub-section in the config file.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1108
> LIBFCREPO-1108: Creating Verify Command

- plastron/models/letter.py
- plastron/models/newspaper.py
- plastron/models/poster.py
- plastron/models/umd.py
- plastron/util.py
- plastron/validation/__init__.py
Adding to the models the handle field, and adding a is_handle function to the utils so that the models can access it
https://umd-dit.atlassian.net/browse/LIBFCREPO-1146
>  LIBFCREPO-1126: Updating models with handle field 

- tests/test_validation.py
Made a simple test that calls is_handle and gave a few example handles.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1169
> LIBFCREPO-1169: Unit test for matching handles

- .gitignore
- plastron-cli/src/plastron/cli/commands/export.py
- plastron-models/src/plastron/serializers/__init__.py
- plastron-rdf/src/plastron/rdfmapping/properties.py
- plastron-rdf/src/plastron/rdfmapping/resources.py
- plastron-repo/src/plastron/jobs/exportjob.py
Updated the command line argument binary-types to split with strings and not to when nothing was provided.
Also updated the usage of the rdf models in the job and various other classes that were used in the export process.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1217
> LIBFCREPO-1217 Updating command line argument and updating access of rdf models

- plastron-cli/src/plastron/cli/commands/update.py
- plastron-cli/tests/test_update_command.py
- plastron-stomp/tests/test_update_command_stomp.py
Removing use of legacy RepositoryList class in the command. And also introducing usage of RepositoryResource instead.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1216
> LIBFCREPO-1216: Refactoring update command

- plastron-cli/src/plastron/cli/commands/reindex.py
https://umd-dit.atlassian.net/browse/LIBFCREPO-1229
> LIBFCREPO-1229: Updating the reindex command to not use RepositoryList

- README.md
- plastron/commands/load.py
- Update to match changes to Batch/BatchItem classes.
- Also, updated a pip instruction to work in zsh.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1231
> LIBFCREPO-1231. Update load.py

- plastron-cli/src/plastron/cli/commands/stub.py
- plastron-models/src/plastron/models/umd.py
- plastron-repo/src/plastron/repo/pcdm.py
https://umd-dit.atlassian.net/browse/LIBFCREPO-1219
> LIBFCREPO-1219: Updating Stub Command to use new Repository Model

- plastron-cli/src/plastron/cli/__init__.py
- plastron-cli/src/plastron/cli/commands/set.py
- plastron-cli/tests/commands/test_set.py
- plastron-utils/src/plastron/utils/__init__.py
- sets one or more fields on one or more objects to a given value or values
https://umd-dit.atlassian.net/browse/LIBFCREPO-1148
> LIBFCREPO-1148. Added "set" command to the CLI.

- plastron-cli/src/plastron/cli/commands/__init__.py
- plastron-models/src/plastron/serializers/csv.py
- plastron-repo/src/plastron/jobs/imports/__init__.py
- plastron-repo/src/plastron/jobs/imports/spreadsheet.py
- plastron-repo/tests/jobs/test_import_job.py
- plastron-repo/tests/jobs/test_import_job/item.csv
- added "PUBLISH" and "HIDDEN" to the list of system columns in the CSV serialization
- default for both if not present or blank is False
- if PUBLISH is True, adds the umdaccess:Published class to the new item
- if HIDDEN is True, adds the umdaccess:Hidden class to the new item
- created Bucket protocol class (Sized, Container) for more appropriate typing of the completed file log
- additional code cleanup in the ImportJob and ImportRun classes
https://umd-dit.atlassian.net/browse/LIBFCREPO-1258
> LIBFCREPO-1258. Add PUBLISH and HIDDEN flags to the import CSV.

- plastron-cli/pyproject.toml
- plastron-models/pyproject.toml
- plastron-utils/requirements.txt
https://umd-dit.atlassian.net/browse/LIBFCREPO-1269
> LIBFCREPO-1269. Pin lxml version.

- plastron-stomp/docs/commands/import.md
- plastron-stomp/src/plastron/stomp/commands/importcommand.py
- plastron-stomp/tests/commands/test_importcommand_stomp.py
Added unit test to verify.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1260
> LIBFCREPO-1260. Add option to publish on load.

- .dockerignore
- plastron-models/src/plastron/models/letter.py
- plastron-models/src/plastron/models/newspaper.py
- plastron-models/src/plastron/models/poster.py
- plastron-repo/src/plastron/jobs/exportjob.py
- plastron-stomp/Dockerfile
- Updated Poster and Issue to new RDF mapping class styles, and correct errors in the Letter class
- Streamlined some of the code in the ExportJob dealing with collecting binaries and creating the zipped bags
- Removed git from the Docker image (all dependencies are now installed from PyPI)
- Updated the .dockerignore for the nested plastron package directories
https://umd-dit.atlassian.net/browse/LIBHYDRA-543
> LIBHYDRA-543. Export job fixes.

- plastron-repo/src/plastron/jobs/importjob/spreadsheet.py
- added type signature to get_final_prop()
https://umd-dit.atlassian.net/browse/LIBFCREPO-1279
> LIBFCREPO-1279. Split attributes on dot in build_fields().

- plastron-models/src/plastron/handles/__init__.py
- plastron-models/tests/test_handles.py
https://umd-dit.atlassian.net/browse/LIBFCREPO-1285
> LIBFCREPO-1285. HandleServiceClient returns None when handle service responds with a 404.

- plastron-cli/tests/commands/test_publish.py
- plastron-models/src/plastron/handles/__init__.py
- plastron-models/tests/test_handles.py
- plastron-repo/src/plastron/jobs/importjob/__init__.py
- plastron-repo/src/plastron/repo/publish.py
- plastron-repo/tests/jobs/test_publication_job.py
- plastron-repo/tests/repo/test_publishable_resource.py
- plastron-web/tests/test_activitystream.py
- reworked the Handle class into the HandleInfo class to return more info from the handle server
- allow updating of fields in addition to url
https://umd-dit.atlassian.net/browse/LIBFCREPO-1335
> LIBFCREPO-1335. Allow updates of other handle fields.

- plastron-models/src/plastron/models/letter.py
- plastron-models/src/plastron/models/poster.py
https://umd-dit.atlassian.net/browse/LIBFCREPO-1562
> LIBFCREPO-1562. Set datatype on the `date` attribute in the Letter model.

- plastron-cli/src/plastron/cli/commands/reindex.py
Based on changes commited here: https://github.com/umd-lib/plastron/commit/7395eaa7e7c50d81050082292ce6c0ae102d69cf#diff-dee39ca5bba32109151a93a88381216581c0ace206cb4a1a7711528e44b0d365R47
https://umd-dit.atlassian.net/browse/LIBFCREPO-1567
> LIBFCREPO-1567: Refactoring reindex class based on changes from broker

- plastron-cli/src/plastron/cli/commands/find.py
https://umd-dit.atlassian.net/browse/LIBFCREPO-1452
> LIBFCREPO-1452: Updating logging for find command

- plastron-models/pyproject.toml
- plastron-models/src/plastron/models/newspaper.py
- plastron-models/src/plastron/validation/rules.py
- plastron-models/src/plastron/validation/vocabularies/__init__.py
- added VocabularyTerm to Issue model
- improve iso-639 support by switching to python-iso639
- added a `find` method to to `Vocabulary` to look up a term by attribute
https://umd-dit.atlassian.net/browse/LIBFCREPO-1496
> LIBFCREPO-1496. Updates to support solrizer facets indexer.

- plastron-repo/src/plastron/repo/pcdm.py
- constructor takes an optional class
- if given, uses as the resource type class to fetch the proxied resources from the repository
https://umd-dit.atlassian.net/browse/LIBFCREPO-1498
> LIBFCREPO-1498. `ProxyIterator` can return full objects.

- plastron-models/pyproject.toml
https://umd-dit.atlassian.net/browse/LIBFCREPO-1578
> LIBFCREPO-1578: Allow ttl to be copied to site packages

- plastron-models/src/plastron/models/fedora.py
- plastron-models/src/plastron/models/letter.py
- plastron-models/src/plastron/models/newspaper.py
- plastron-models/src/plastron/models/poster.py
- plastron-models/src/plastron/models/umd.py
- added created_by and last_modified_by properties
- added FedoraResource as a base class for the model classes
- added HandleBearingResource to the Issue and Poster model classes
- removed redundant handle property from the model classes
https://umd-dit.atlassian.net/browse/LIBFCREPO-1503
> LIBFCREPO-1503. Expanded the FedoraResource RDF mapping class.

- plastron-models/pyproject.toml
- plastron-models/src/plastron/models/umd.py
https://umd-dit.atlassian.net/browse/LIBFCREPO-1594
> LIBFCREPO-1594. Made AdminSet a non-top-level content-modeled resource.

- plastron-models/src/plastron/models/newspaper.py
- plastron-models/tests/test_issue_model.py
Required, and from the UMD rights statements vocabulary.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1607
> LIBFCREPO-1607. Added "rights" property to the Issue model.

- plastron-models/src/plastron/ocr/__init__.py
- plastron-models/src/plastron/ocr/core.py
- plastron-repo/src/plastron/repo/__init__.py
https://umd-dit.atlassian.net/browse/LIBFCREPO-1626
> LIBFCREPO-1626. Catch errors in the ImageWithOCR class.

- plastron-repo/src/plastron/repo/__init__.py
- plastron-repo/tests/repo/test_resource.py
https://umd-dit.atlassian.net/browse/LIBFCREPO-1634
> LIBFCREPO-1634. Added `convert_to` method to RepositoryResource.
